PyrusApp/PyrusApp/Models/ItemSearchViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PyrusApp.Models
{
    public class ItemSearchViewModel
    {
        public List<SelectListItem> Cities { get; set; }
        public List<SelectListItem> Categories { get; set; }
        public CraigslistSearch Search { get; set; }
    }
}

PyrusApp/PyrusApp/Models/SavedResultsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PyrusApp.Models
{
    public class SavedResultsViewModel
    {

       public LinkedList<CraigslistAd> SavedAds { get; set; }
       public Dictionary<string, string> AdNotes { get; set; }
    }
}

PyrusApp/PyrusApp/Models/SearchViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PyrusApp.Models
{
    public class SearchViewModel
    {
        public List<SelectListItem> Cities { get; set; }
        public List<SelectListItem> Categories { get; set; }

    }
}

PyrusApp/PyrusApp/Controllers/CraigslistController.cs
using PyrusApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Threading.Tasks;
using System.Diagnostics;
using System.Xml.Linq;
using System.Xml;
using HtmlAgilityPack;
using System.Net;
using System.IO;
using System.Threading;
using System.Collections;

namespace PyrusApp.Controllers
{
    

    [Authorize]
    public class CraigslistController : Controller
    {
        CraigslistContext database = new CraigslistContext();
        //static LinkedList<CraigslistAd> savedAds;


        [HttpGet]
        public ViewResult Search()
        {
            CraigslistSearchViewModel model = new CraigslistSearchViewModel();
            model.Cities = new MultiSelectList(database.Cities.ToList().OrderBy(city => city.StateName), "ID", "CityName", "StateName");
            model.Categories = new MultiSelectList(database.Categories.ToList().OrderBy(category => category.CategoryName), "ID", "CategoryName");
            model.Search = new CraigslistSearch();
            return View(model);
        }

        [HttpPost]
        public ActionResult Search(CraigslistSearch search)
        {
            
            List<String> CityExtensions = new List<String>();
            List<String> CityNames = new List<String>();

            foreach (int cityID in search.Cities)
            {
                CityExtensions.Add(database.Cities.FirstOrDefault(c => c.ID == cityID).Extension);
                CityNames.Add(database.Cities.FirstOrDefault(c => c.ID == cityID).CityName);
            }

            List<String> CategoryExtensions = new List<String>();
            List<String> CategoryNames = new List<String>();

            foreach (int categoryID in search.Categories)
            {
                CategoryExtensions.Add(database.Categories.FirstOrDefault(c => c.ID == categoryID).Extension);
                CategoryNames.Add(database.Categories.FirstOrDefault(c => c.ID == categoryID).CategoryName);
            }

            //Queue of string tuples that define the information parseFeed needs
            Queue<string[]> urlCityCategoryTuples = new Queue<string[]>();
            for (int i = 0; i < CityExtensions.Count; i++)
            {
                for (int j = 0; j < CategoryExtensions.Count; j++)
                {
                    string minPrice = "", maxPrice = "", hasImage = "";

                    if (search.MinPrice != null)
                    {
                        minPrice = "&min_price=" + search.MinPrice;
                    }
                    if (search.MaxPrice != null)
                    {
                        maxPrice = "&max_price=" + search.MaxPrice;
                    }
                    if (search.HasImage)
                    {
                        hasImage = "&hasPic=1";
                    }
                    urlCityCategoryTuples.Enqueue(
                        new string[3] {"https://" + CityExtensions[i] + ".craigslist.org/search/" +
                        CategoryExtensions[j] + "?query=" + search.Query + minPrice + maxPrice + hasImage + "&format=rss",
                        CityNames[i],
                        CategoryNames[j]
                    });

                }
            }

            LinkedList<CraigslistAd> ads = new LinkedList<CraigslistAd>();
            int numUrls = urlCityCategoryTuples.Count;
            //Manage numUrls logic here
            //
            //
            //
            //
            //

            Parallel.For(0, numUrls, index =>
            {
                string[] urlCityCategoryTuple = urlCityCategoryTuples.Dequeue();
                CraigslistUtilities.parseFeed(urlCityCategoryTuple, ads);
            });



            StringBuilder CitiesBuilder = new StringBuilder();
            StringBuilder CategoriesBuilder = new StringBuilder();

            foreach (string city in CityNames)
            {
                CitiesBuilder.Append(city + "\n");
            }

            foreach (string category in CategoryNames)
            {
                CategoriesBuilder.Append(category + "\n");
            }

            ViewBag.CityNames = CitiesBuilder.ToString();
            ViewBag.CategoryNames = CategoriesBuilder.ToString();
            ViewBag.Query = search.Query;

            return PartialView("Results", ads.AsEnumerable<CraigslistAd>());
        }

        /*
        public ActionResult SavedResults()
        {

            return View(savedAds);

        }

        public ActionResult EditNote(string URL)
        {
            var ad = savedAds.Where(item => item.URL == URL).FirstOrDefault();

            return View(ad);
        }

        [HttpPost]
        public ActionResult EditNote(string URL, string Notes)
        {
            savedAds.Where(item => item.URL == URL).FirstOrDefault().Notes = Notes;
            return RedirectToAction("SavedResults", savedAds);
        }
        */
    }
}

PyrusApp/PyrusApp/Views/Craigslist/BoxPlot.cshtml
@model IEnumerable<PyrusApp.Models.CraigslistAd>

<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
<div id="boxPlot"><!-- Plotly chart will be drawn inside this DIV --></div>
</script>

<script>

    var x = {};
    @{
        var sortedModel = Model.OrderBy(modelItem => modelItem.AskingPrice);
        var prices = new int?[@Model.Count()];

        for (int i = 0; i < Model.Count(); i++)
        {
            prices[i] = sortedModel.ElementAt(i).AskingPrice;
        }
    }

    x = @Html.Raw(Json.Encode(prices));
    var trace1 = {
        x,
        type: 'box',
        name: 'US Dollars'
    };

    var data = [trace1]

    var layout = {
        title: 'Price Box and Whiskers chart'
    };

    Plotly.newPlot('boxPlot', data, layout);
</script>

PyrusApp/PyrusApp/Views/Craigslist/CraigslistSearchAjaxForm.cshtml
@model PyrusApp.Models.CraigslistSearchViewModel

@using (Ajax.BeginForm("Search", "Craigslist", new AjaxOptions
            {
                HttpMethod = "POST",
                OnSuccess = "updateResults",


            },
            new { id = "craigslistSearchForm" }))
{


<div class="form-horizontal">
    <h4>CraigslistAd</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(model => model.Search.Cities, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.ListBoxFor(model => model.Search.Cities, Model.Cities, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Search.Cities, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Search.Categories, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.ListBoxFor(model => model.Search.Categories, Model.Categories, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Categories, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Search.URL, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.URL, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.URL, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.SmallImageURL, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.SmallImageURL, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.SmallImageURL, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ThumbnailImageURL, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ThumbnailImageURL, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ThumbnailImageURL, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.MediumImageURL, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.MediumImageURL, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.MediumImageURL, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.BigImageURL, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.BigImageURL, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.BigImageURL, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.TimeStamp, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.TimeStamp, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TimeStamp, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PartialDescription, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.PartialDescription, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PartialDescription, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.AskingPrice, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.AskingPrice, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.AskingPrice, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Search" class="btn btn-default" />
        </div>
    </div>
</div>
}

PyrusApp/PyrusApp/Views/Craigslist/EditNote.cshtml
@model PyrusApp.Models.CraigslistAd

@{
    ViewBag.Title = "EditNote";
}

<h2>EditNote</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>@Html.DisplayNameFor(model => model.Title) Notes</h4>

                @Html.HiddenFor(model => model.URL)

        <div class="form-group">
            @Html.LabelFor(model => model.Notes, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Notes, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Notes, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

PyrusApp/PyrusApp/Views/Craigslist/ItemSearch.cshtml
@model PyrusApp.Models.ItemSearchViewModel

PyrusApp/PyrusApp/Views/Craigslist/Results.cshtml
@model IEnumerable<PyrusApp.Models.CraigslistAd>

<table class="display col-lg-12" id="resultsTable">
    <thead>
        <tr>
            <th>
                @*Placeholder for hidden price column*@
            </th>
            <th id="resultsTableHeader">
                @*@Html.DisplayNameFor(model => model.Title)*@
            </th>

        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model)
        {


            <tr >
                <td>
                    @Html.DisplayFor(modelItem => item.AskingPrice)
                </td>

                <td id="resultsTableRow">
                    <div id="resultTitle" class="row">

                        <div class="cityAndCategoryContainer">
                            <span class="city">@Html.DisplayFor(modelItem => item.City)</span>
                            <span class="category">@Html.DisplayFor(modelItem => item.Category)</span>
                        </div>

                        <a href=@Html.DisplayFor(modelItem => item.URL) target="_blank">
                             @Html.DisplayFor(modelItem => item.Title)
                        </a>

                        @if (@Html.DisplayFor(modelItem => item.AskingPrice).ToString() != "")
                        {
                            <span class="price">$@Html.DisplayFor(modelItem => item.AskingPrice)</span>
                        }
                        else
                        {
                            //<span class="priceNotListed">Price not listed</span>
                        }
                        @{ 
                            var timeStamp = @Html.DisplayFor(modelItem => item.TimeStamp).ToString();
                            var dateTime = System.Convert.ToDateTime(timeStamp);



                         }
                        <div class="dateContainer">


                            <span class="date">@dateTime.Date</span>
                        </div>






</div>

                    <div class="row">

                            <div class="col-lg-4">
                                <a href=@Html.DisplayFor(modelItem => item.URL) target="_blank">

                                    <img class="itemPhoto" src=@if(@Html.DisplayFor(modelItem => item.SmallImageURL).ToString() != "")
                                 {
                                     @Html.DisplayFor(modelItem => item.SmallImageURL);
                                 }
                                 else
                                 {
                                     @Url.Content("~/images/no_image.png");
                                 }
                                         class="thumbnail">
                                </a>
                            </div>

                            <div class="col-lg-8">

                                <p id="description">@Html.DisplayFor(modelItem => item.PartialDescription)</p>
                            </div>

                    </div>
 
                </td>

            </tr>
        }
    </tbody>

</table>

PyrusApp/PyrusApp/Views/Craigslist/SavedResults.cshtml
@model LinkedList<PyrusApp.Models.CraigslistAd>


<table class="display" id="resultsTable">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.First().AskingPrice)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.First().Title)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.First().Notes)
            </th>

        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model)
        {


            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.AskingPrice)
                </td>

                <td>

                        <a href=@Html.DisplayFor(modelItem => item.URL) target="_blank">
                            @Html.DisplayFor(modelItem => item.Title)
                        </a>
                        <div class="cityAndCategoryContainer">
                            <span class="city">@Html.DisplayFor(modelItem => item.City)</span>
                            <span class="category">@Html.DisplayFor(modelItem => item.Category)</span>
                        </div>

                        

                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.Notes)
                    <br>
                    @Html.ActionLink("Edit Note", "EditNote", new {URL = item.URL})
                </td>

            </tr>
                            }
    </tbody>

</table>



@section scripts{



    <script>

        $(document).ready(function () {
            var table = $("#resultsTable").DataTable({
                "deferRender": true,
                "autoWidth": false,
                "columnDefs": [
                {
                    "targets": [0],
                    "width": "5%"

                },
                {
                    "targets": [1],
                    "width": "55%"
                },
                {
                    "targets": [2],
                    "width":"40%"
                }
                ]
            });

        });




    </script>
}

PyrusApp/PyrusApp/Views/Craigslist/Search.cshtml
@model PyrusApp.Models.CraigslistSearchViewModel

        <div class="col-lg-12" id="craigslistSearchDiv">

            @using (Ajax.BeginForm("Search", "Craigslist",
                                        new AjaxOptions
                                        {
                                            HttpMethod = "POST",
                                            InsertionMode = InsertionMode.Replace,
                                            OnBegin = "clearValidation",
                                            OnSuccess = "updateResults",
                                            LoadingElementId = "loading"
                                        },
                                        new { id = "craigslistSearchForm" }


                                    ))
            {
                <div class="row">
                    <div class="col-sm-4">
                          <h2 id="craigslistSearchBarTitle">Craigslist Search Aggregator</h2>
                    </div>
                </div>

                @Html.ValidationSummary(false, "", new { @class = "text-danger", id = "validationMessage" })

                <div class="row">


                    <div class="col-sm-4">

                        <div class="form-group">
                            @Html.LabelFor(model => model.Search.Cities, new { @class = "searchLabel" })
                            <br />
                            @Html.ListBoxFor(model => model.Search.Cities, Model.Cities, new { @class = "form-control", id = "cityList", data_placeholder = "Select cities..." })
                        </div>

                        <div class="form-group">
                            @Html.Label("Price Range (USD)", new { @class = "searchLabel" })
                            <br />
                            @Html.TextBoxFor(model => model.Search.MinPrice, Model.Search.MinPrice.ToString(), new { placeholder = "Min", @class = "form-control" })
                            @Html.TextBoxFor(model => model.Search.MaxPrice, Model.Search.MaxPrice.ToString(), new { placeholder = "Max", @class = "form-control" })
                        </div>

                    </div>



                    <div class="col-sm-4">

                        <div class="form-group">
                            @Html.LabelFor(model => model.Search.Categories, new { @class = "searchLabel" })
                            <br />
                            @Html.ListBoxFor(model => model.Search.Categories, Model.Categories, new { @class = "form-control", id = "categoryList", data_placeholder = "Select categories..." })
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Search.HasImage, new { @class = "searchLabel", id = "imageOnly" })
                            @Html.CheckBoxFor(model => model.Search.HasImage, Model.Search.HasImage)
                        </div>


                    </div>
                    <div class="col-sm-4">



                        <div class="form-group">
                            @Html.LabelFor(model => model.Search.Query, new { @class = "searchLabel" })
                            @Html.TextBoxFor(model => model.Search.Query, Model.Search.Query, new { @class = "form-control" })
                            <!-- Button trigger modal -->
                            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#advancedSearchDialog">
                                Advanced Search Options
                            </button>
                            <input type="submit" id="craigslistSubmitButton" value="Search" class="btn btn-default" />
                                

                            
                        </div>
                    </div>
                </div>



            }
            @{Html.EndForm();}
        </div>

    <div class="col-sm-12" id="wait">
        <img src='~/images/spinner.gif' />
        <h6>Loading...</h6>
    </div>

    <div class="col-lg-12" id="searchResults"></div>
    <div id="advancedSearchOptions"></div>

     <!-- Modal -->
    <div class="modal fade" id="advancedSearchDialog" tabindex="-1" role="dialog" aria-labelledby="advancedSearchDialogTitle" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h3 class="modal-title" id="advancedSearchDialogTitle">Advanced Search</h3>

                </div>
                <div class="modal-body">

                    <p>
                        <div>
                            <strong>Phrase Search:</strong> <em>"low miles"</em>
                            <h6>You can use quotation marks to search for a phrase.</h6>
                        </div>
                        <div>
                            <strong>Excluding Terms:</strong> <em>honda black -red</em>
                            <h6>This search finds postings that have 'honda' and 'black' but not 'red'. </h6>
                        </div>
                        <div>
                            <strong>"OR" Search: </strong> <em>honda | toyota</em>
                            <ul>
                                <li>This search finds postings that have 'honda' or 'toyota' (or both).</li>
                            </ul>
                        </div>
                        <div>
                            <strong>Grouping: </strong> <em>red (toyota | honda) -2000 -2001</em>
                            <ul>
                                <li>You can group terms together in parenthesis when queries are complicated.</li>
                                <li>This finds listings that have 'red' and either 'honda' or 'toyota' (or both) but do not have 2000 or 2001.</li>
                            </ul>
                        </div>
                        <div>
                            <strong>Wildcards: </strong>
                            <em>
                                <ul>
                                    <li>hond* civ*  (match "honda civic", "honda civil", etc)</li>
                                    <li>wood floo* (matches "wood floors," "wood flooring", etc)</li>
                                    <li>iphone* (matches "iphone," "iphones," "iphone5," etc)</li>
                                </ul>
                            </em>
                        </div>
                    </p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>

@section scripts{

    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <script>//cdn.datatables.net/plug-ins/1.10.15/sorting/datetime-moment.js</script>


    <script>
    $.validator.setDefaults({
        ignore: []
    });

    $(document).ready(function () {
        $("#cityList, #categoryList").chosen();
        $("#searchResults, #advancedSearchOptions").hide();

        /* code for adding spinner ,ajaxComplete and ajax start */
        $(document).ajaxStart(function () {
            $("#searchResults").hide();
            $("#wait").css("display", "block");
        });
        $(document).ajaxComplete(function () {

            $("#wait").css("display", "none");


        });
        $('[data-toggle="tooltip"]').tooltip(
            {
                trigger: 'click',
                trigger: 'hover',
                placement: 'bottom'
            })

    });

    function clearValidation() {
        $("#validationMessage ul li").remove();
    }

    function updateResults(response) {
        $("#searchResults").html(response);
        var table = $("#resultsTable").DataTable({
            "deferRender": true,
            "autoWidth": false,
            "language":
                {
                    "search": "Instant Subsearch:"
                }
            ,
            "columnDefs": [
            {
                    "targets": [0],
                "visible": false,
                "searchable": false
            },
            {
                "targets": [1],
                "width": "100%"
            }
            ]


        });
        $('div.dataTables_filter input').addClass('form-control');
        $("#resultsTable_length, #resultsTableHeader").hide();
        $("#advancedSearchOptions, #searchResults").fadeIn(2000);
    };

    </script>
}

PyrusApp/PyrusApp/Views/Craigslist/Search1.cshtml
@model PyrusApp.Models.CraigslistSearch

@using (Ajax.BeginForm("Search", "Craigslist", new AjaxOptions
{
    HttpMethod = "POST",
    InsertionMode = InsertionMode.Replace,
    OnSuccess = "updateResults"

    }
))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CraigslistSearch</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Query, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Query, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Query, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HasImage, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.HasImage)
                    @Html.ValidationMessageFor(model => model.HasImage, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MinPrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MinPrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MinPrice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaxPrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaxPrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaxPrice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

PyrusApp/PyrusApp/Views/Craigslist/TableChart.cshtml
@model IEnumerable<PyrusApp.Models.CraigslistAd>

<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<div id="tableChart"></div>
<script>
    google.charts.load('current', { 'packages': ['table'] });
    google.charts.setOnLoadCallback(drawTable);

    @{
            List<object> rows = new List<object> ();

            foreach(PyrusApp.Models.CraigslistAd ad in Model)
            {
                rows.Add(new { ad.Title, ad.AskingPrice, ad.City, ad.Category, ad.TimeStamp });
            }
        }
        function drawTable() {
            var data = new google.visualization.DataTable();
            data.addColumn('string', 'Title');
            data.addColumn('number', 'Price');
            data.addColumn('string', 'City');
            data.addColumn('string', 'Category');
            data.addColumn('string', 'Time Stamp')

            alert(rowsArray);

            data.addRows(rowsArray);



        var table = new google.visualization.Table(document.getElementById('tableChart'));

            table.draw(data, { showRowNumber: true, width: '100%', height: '100%' });
        }


</script>

PyrusApp/PyrusApp/Views/Craigslist/Temp1.cshtml
@model PyrusApp.Models.CraigslistSearchViewModel

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CraigslistSearchViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>