PyrusApp/PyrusApp/Models/JobSearch.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.Text.RegularExpressions;
using System.Web.Mvc;

namespace PyrusApp.Models
{
    public class JobSearch
    {
        /*
        public enum JobType
        {
            All,
            FullTime,
            PartTime,
            Contract,
            Internship,
            Temporary
        }
        */
        //[Required]
        [Display(Name ="Search:")]
        public string Query { get; set; }

        [Required]
        [Display(Name ="Cities:")]
        public List<int> CityIDs { get; set; }

        public List<City> Cities { get; set; }

    }
}

PyrusApp/PyrusApp/Models/JobSearchViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PyrusApp.Models
{
    public class JobSearchViewModel
    {
        public JobSearch JobSearch { get; set; }
        public MultiSelectList Cities { get; set; }
    }
}

PyrusApp/PyrusApp/Models/SearchViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PyrusApp.Models
{
    public class SearchViewModel
    {
        public List<SelectListItem> Cities { get; set; }
        public List<SelectListItem> Categories { get; set; }

    }
}

PyrusApp/PyrusApp/Controllers/JobSearchController.cs
using PyrusApp.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PyrusApp.Controllers
{
    [Authorize]
    public class JobSearchController : Controller
    {
        CraigslistContext database = new CraigslistContext();
        // GET: JobSearch
        public ActionResult Search()
        {
            var model = new JobSearchViewModel();
            model.JobSearch = new JobSearch();
            model.Cities = new MultiSelectList(database.Cities.ToList().OrderBy(city => city.StateName), "ID", "CityName", "StateName");

            return View(model);
        }

        // Post: JobSearch
        [HttpPost]
        public ActionResult Search(JobSearch jobSearch)
        {
            int pages = 5;
            jobSearch.Cities = new List<City>();

            var ads = new List<AdType>();

            foreach(var cityID in jobSearch.CityIDs)
            {
                jobSearch.Cities.Add(database.Cities.FirstOrDefault(city => city.ID == cityID));
            }


            List<LocationAndURL> locationsAndURLs = IndeedUtilities.BuildJobSearchBaseURlsWithLocations(jobSearch, Request, pages);
           

            
            foreach (var locationAndURL in locationsAndURLs)
            {

                foreach (var result in IndeedUtilities.Results(locationAndURL.URL))
                {
                    var ad = IndeedUtilities.parseResult(result, locationAndURL.Location);
                    if(ad != null)
                    {
                        ads.Add(ad);
                    }
                    
                }
            }
            

            locationsAndURLs = MonsterUtilities.BuildJobSearchBaseURlsWithLocations(jobSearch, pages);
            foreach (var locationAndURL in locationsAndURLs)
            { 
                foreach (var result in MonsterUtilities.Results(locationAndURL.URL))
                {
                    var ad = MonsterUtilities.parseResult(result, locationAndURL.Location);
                    if(ad != null)
                    {
                        ads.Add(ad);
                    }
                    
                }
            }
            
            List<Tuple<string, string, string>> urlCityCategoryTupleList = new List<Tuple<string,string,string>>();

            foreach(var city in jobSearch.Cities)
            {
                urlCityCategoryTupleList.Add(new Tuple<string, string, string>
                    ("https://" + city.Extension +
                    ".craigslist.org/search/"
                    + "jjj" + "?query=" + jobSearch.Query + "&format=rss", city.CityName,
                    "Jobs"));
            }
            var craigslistAdResults = new LinkedList<CraigslistAd>();
            foreach(var urlCityCategoryTuple in urlCityCategoryTupleList)
            {
                craigslistAdResults = CraigslistUtilities.parseFeed(new string[3] { urlCityCategoryTuple.Item1,
                urlCityCategoryTuple.Item2, urlCityCategoryTuple.Item3}, craigslistAdResults);
            }

            Debug.WriteLine(craigslistAdResults.Count());
            foreach(var craigslistAd in craigslistAdResults)
            {
                ads.Add(new AdType
                {
                    Title = craigslistAd.Title,
                    Network = "Craigslist",
                    Description = craigslistAd.PartialDescription,
                    Date = craigslistAd.TimeStamp,
                    Location = craigslistAd.City,
                    URL = craigslistAd.URL
                });
            }

            return PartialView("Results",ads);

        }
    }
}

PyrusApp/PyrusApp/Views/JobSearch/Index.cshtml
@model PyrusApp.Models.JobSearch

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>JobSearch</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Query, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Query, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Query, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

PyrusApp/PyrusApp/Views/JobSearch/Results.cshtml
@model IEnumerable<PyrusApp.Models.AdType>

<table class="display" id="myTable">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Location)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>

        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <a href=@Html.DisplayFor(modelItem => item.URL) target="_blank"> @Html.DisplayFor(modelItem => item.Title)</a>
                    <h4>@Html.DisplayFor(modelItem => item.Network)</h4>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Location)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Date)
                </td>

            </tr>
        }
    </tbody>
</table>

PyrusApp/PyrusApp/Views/JobSearch/Search.cshtml
@model PyrusApp.Models.JobSearchViewModel

@{
    ViewBag.Title = "Search";
}

<div class="row">

    @using (Ajax.BeginForm("Search", "JobSearch",
                                new AjaxOptions
                                {
                                    HttpMethod = "POST",
                                    InsertionMode = InsertionMode.Replace,
                                    OnSuccess = "updateResults",
                                    LoadingElementId = "loading"
                                },
                                new { id = "craigslistSearchForm", @class="form-inline"}


                            ))
    {
        <h3>Job Search</h3>

        @Html.ValidationSummary(false, "", new { @class = "text-danger", id = "validationMessage" })


        <div class="form-group">
            @Html.LabelFor(model => model.JobSearch.CityIDs)
            @Html.ListBoxFor(model => model.JobSearch.CityIDs, Model.Cities, new { @class = "form-control", id = "zipCodeList", data_placeholder = "Select cities..." })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.JobSearch.Query)
            @Html.TextBoxFor(model => model.JobSearch.Query, Model.JobSearch.Query, new { @class = "form-control" })
            <input type="submit" value="Search" class="btn btn-default" />
        </div>
    }
    @{Html.EndForm();}
</div>
<div class="row" id="searchResults">
</div>



@section scripts{

    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>


    <script>
    $.validator.setDefaults({
        ignore: []
    });

    $(document).ready(function () {
        $("#zipCodeList").chosen();
        $("#searchResults").hide();

        $(document).ajaxStart(function () {

            $("#searchResults").hide();
            $("#wait").css("display", "block");
        });
        $(document).ajaxComplete(function () {
            $("#searchResults").fadeIn(2000);
            $("#wait").css("display", "none");
        });

    });

    function updateResults(response) {
        $("#validationMessage").hide();
        //Problem here
        $("#searchResults").html(response);
        $("#myTable").DataTable();



    };




    </script>
}


<div id="wait" style="display:none;width:69px;height:89px;position:absolute;top:50%;left:50%;padding:2px;"><img src='~/images/spinner.gif' width="64" height="64" /><br>Loading..</div>